name: Build

on:
  pull_request:
    paths:
      - "src/**"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: |
          docker build --build-arg K8SVERSION=$GITHUB_SHA -t ghcr.io/marklechtermann/k8sdisturber:latest -t ghcr.io/marklechtermann/k8sdisturber:$(date +%Y%m%d).$(echo $GITHUB_SHA | cut -c -7) .
