name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build -t marklechtermann/k8sdisturber:latest -t marklechtermann/k8sdisturber:$(date +%Y%m%d).$(echo $GITHUB_SHA | cut -c -7) .
      - name: Docker Push
        run: docker push marklechtermann/k8sdisturber:latest -t marklechtermann/k8sdisturber:$(date +%Y%m%d).$(echo $GITHUB_SHA | cut -c -7)
      - name: Docker Logout
        run: docker logout
