name: CI

on:
  push:
    branches: 
      - master
    paths:
      - "src/**"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: |
          docker build --build-arg K8SVERSION=$GITHUB_SHA -t marklechtermann/k8sdisturber:latest -t marklechtermann/k8sdisturber:$(date +%Y%m%d).$(echo $GITHUB_SHA | cut -c -7) .
      - name: Docker Push
        run: |
          docker push marklechtermann/k8sdisturber:latest 
          docker push marklechtermann/k8sdisturber:$(date +%Y%m%d).$(echo $GITHUB_SHA | cut -c -7)
      - name: Docker Logout
        if: always()
        run: docker logout
